### ISSUE TITLE
Any guide or Documentation to implement and using this lib

### ISSUE THREAD

**Issue by maxrave-dev** [yuliskov/MediaServiceCore#8]
Hope you build a documentation or a guide to use this library

**Comment by yuliskov** [comment]
I want to create the doc too but let's be real, this possibly never happen.
There's so small demand for this. I think the only option to learn the api
will remain the main app.

Regards, Yuriy

**Comment by maxrave-dev** [comment]
Thanks, I am trying to see how to implement this in SmartTube repo.
